version: '3.3'

services:

  api-cashback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-cashback
#    command: python que roda o flaskzin
#    volume:
#      - ver se coloco o sqlite
    ports:
      - 9095:5000

#  db-api-cashback:
#    container_name: db-api-cashback
#    image: redis
#    ports:
#      - "6379:6379"
#    command: redis-server --requirepass CashB4ckAp1!

networks:
  cashback:

