version: '3.3'

services:

  api-cashback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-cashback
    environment:
      - SQLITE_FILE=/app/db.sqlite3
    ports:
      - 9785:5000
    networks:
      - cashback
#    command: FLASK_APP=api.py flask run --host=0.0.0.0

networks:
  cashback:

