version: '3.3'

services:

  api-cashback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-cashback
    environment:
      - SQLITE_FILE=/app/db.sqlite3
    ports:
      - 9785:5000
    networks:
      - cashback

networks:
  cashback:

