version: '3.3'

services:

  api-cashback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-cashback
    command: FLASK_APP=app/api.py flask run --host=0.0.0.0
    ports:
      - 9785:5000

networks:
  cashback:

